server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:bitcoin-ms.jks
    key-store-password: 123456
    key-alias: bitcoin-ms
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:bitcoin-ms.jks
    trust-store-password: 123456
    trust-store-type: JKS