package com.la.model.enums;

public enum PublishStatus {
    WAITING_SUBMIT,
    WAITING_PLAGIARISM_CHECK,
    WAITING_READING,
    WAITING_AFTER_READING,
    WAITING_BETA_READERS,
    WAITING_COMMENT_CHECK,
    WAITING_LECTOR_REVIEW,
    WAITING_CORRECTION,
    WAITING_SUGGESTIONS,
    WAITING_CHANGES,
}
