camunda.bpm:
  authorization:
    enabled: true
  admin-user:
    id: admin
    password: admin
    firstName: Admin

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:literary-association.jks
    key-store-password: 123456
    key-alias: literary-association
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:literary-association.jks
    trust-store-password: 123456
    trust-store-type: JKS