export const USER_ROLES = {
    WRITER_MEMBERSHIP_REQUEST: "WRITER_MEMBERSHIP_REQUEST",
    WRITER: "WRITER",
    ADMIN: "ADMIN",
    READER: "READER",
    LECTOR: "LECTOR",
    BOARD_MEMBER: "BOARD_MEMBER",
    EDITOR: "EDITOR"
}